package Parameters;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Scanner;

import Client.FileOperator;
/*
 * Klasa przechowuj¹ca wszystkie parametry wymiarów i umiejscowienia obiektów, jaki i ró¿ne inne paramtry otrzymywane z pliku konfiguracyjknego. klasa ta definiuje w jakiej kolejnoœci interpretowaæ dane z pliku konfiguracyjnego.
 */
public class Dimensions {
	
	public int FRAME_WIDTH;
	public int FRAME_HEIGHT;
	public int GAME_F_DIM;
	public int GAME_DIM;
	public int GAME_START;
	public int OBJ_DIM;
	public int BGD_CLR_A;
	public int BGD_CLR_B;
	public int BGD_CLR_C;
	public int FRAME_HEIGHT_GUI;
	public int WEIRD_X_CONSTANT;
	public int WEIRD_Y_CONSTANT;
	public int ANOTHER_WEIRD_Y_CONSTANT;
	public int BOMBBAR_X_MAIN;
	public int BOMBBAR_Y_MAIN;
	public int BOMBBAR_SX_MAIN;
	public int BOMBBAR_SY_MAIN;
	public int BOMBBAR_X_B1;
	public int BOMBBAR_Y_B1;
	public int BOMBBAR_SX_B1;
	public int BOMBBAR_SY_B1;
	public int BOMBBAR_X_B2;
	public int BOMBBAR_Y_B2;
	public int BOMBBAR_SX_B2;
	public int BOMBBAR_SY_B2;
	public int BOMBBAR_X_B3;
	public int BOMBBAR_Y_B3;
	public int BOMBBAR_SX_B3;
	public int BOMBBAR_SY_B3;
	public int BOMBBAR_X_B4;
	public int BOMBBAR_Y_B4;
	public int BOMBBAR_SX_B4;
	public int BOMBBAR_SY_B4;
	public int BOMBBAR_X_B5;
	public int BOMBBAR_Y_B5;
	public int BOMBBAR_SX_B5;
	public int BOMBBAR_SY_B5;
	public int HPBAR_XY_MAIN;
	public int HPBAR_XS_MAIN;
	public int HPBAR_SIZE;
	public int HPBAR_X_1;
	public int HPBAR_X_2;
	public int HPBAR_X_3;
	public int HPBAR_X_4;
	public int HPBAR_X_5;
	public int HPBAR_Y;
	public int KG_FRAME_WIDTH;
    public int KG_FRAME_HEIGHT;
    public int KG_B1_X;
    public int KG_B_Y;
    public int KG_B_WIDTH;
    public int KG_B_HEIGHT;
    public int KG_B2_X;
    public int KG_T_X;
    public int KG_T_Y;
    public int KG_T_WIDTH;
    public int KG_T_HEIGHT;
    public int KG_FONT_SIZE;
    public int KG_FONTB_SIZE;
    public int KG_L1_X;
    public int KG_L1_Y;
    public int KG_L1_HEIGHT;
    public int KG_L1_WIDTH;
    
    public int KG_L2_X;
    public int KG_L2_Y;
    public int KG_L2_HEIGHT;
    public int KG_L2_WIDTH;
    
    public int KG_L3_X;
    public int KG_L3_Y;
    public int KG_L3_HEIGHT;
    public int KG_L3_WIDTH;
    
    public int KG_L4_X;
    public int KG_L4_Y;
    public int KG_L4_HEIGHT;
    public int KG_L4_WIDTH;
    
    public int KG_TF_X;
    public int KG_TF_Y;
    public int KG_TF_HEIGHT;
    public int KG_TF_WIDTH;
    public int MAIN_FRAME_WIDTH ;
    public int MAIN_FRAME_HEIGHT ;
    public int B_WIDTH ;
    public int B_HIGH ;
    public int B_X ;
    public int B1_Y ;
    public int B2_Y ;
    public int B3_Y ;
    public int B4_Y ;
    public int ANIMATIONS_CNT ;
    public int SCOREBAR_X_MAIN;
	public int SCOREBAR_Y_MAIN;
	public int SCOREBAR_XS_MAIN;
	public int SCOREBAR_YS_MAIN;
	public int SCOREBAR_X_ST;
	public int SCOREBAR_Y_ST;
	public int SCOREBAR_XS_ST;
	public int SCOREBAR_YS_ST;
	public int SCOREBAR_X_VAR;
	public int SCOREBAR_Y_VAR;
	public int SCOREBAR_XS_VAR;
	public int SCOREBAR_YS_VAR;
	
    public int TIMEBAR_X_MAIN;
	public int TIMEBAR_Y_MAIN;
	public int TIMEBAR_XS_MAIN;
	public int TIMEBAR_YS_MAIN;
	public int TIMEBAR_X_ST;
	public int TIMEBAR_Y_ST;
	public int TIMEBAR_XS_ST;
	public int TIMEBAR_YS_ST;
	public int TIMEBAR_X_VAR;
	public int TIMEBAR_Y_VAR;
	public int TIMEBAR_XS_VAR;
	public int TIMEBAR_YS_VAR;
	
	public int W_FRAME_WIDTH;
    public int W_FRAME_HEIGHT;
    public int W_B1_X;
    public int W_B_Y;
    public int W_B_WIDTH;
    public int W_B_HEIGHT;
    public int W_B2_X;
    public int W_T_X;
    public int W_T_Y;
    public int W_T_WIDTH;
    public int W_T_HEIGHT;
    public int W_FONT_SIZE;
    public int W_FONTB_SIZE;
	
    public int S_FRAME_WIDTH;
    public int S_FRAME_HEIGHT;
    public int S_FONT_SIZE;
    public int S_FONTS_SIZE;
    public int S_T_X;
    public int S_T_Y;
    public int S_T_WIDTH;
    public int S_T_HEIGHT;
    public int S_SCROLL_X;
    public int S_SCROLL_Y;
    public int S_SCROLL_WIDTH;
    public int S_SCROLL_HEIGHT;
    
    public int SS_FRAME_WIDTH;
    public int SS_FRAME_HEIGHT;
    public int SS_SIZE;
    public int SS_SPACE_HEIGHT;
    public int SS_SPACE_WIDTH;
    public int SS_FRONT_X;
    public int SS_BACK_X;
    public int SS_LEFT_X;
    public int SS_RIGHT_X;
    public int SS_W_X;
    public int SS_A_X;
    public int SS_S_X;
    public int SS_D_X;
    public int SS_SPACE_X;
    public int SS_ESC_X;
    public int SS_BOMB_X;
    public int SS_Q_X;
    public int SS_E_X;
    public int SS_T1_X;
    public int SS_T2_X;
    public int SS_T3_X;
    public int SS_FRONT_Y;
    public int SS_BACK_Y;
    public int SS_LEFT_Y;
    public int SS_RIGHT_Y;
    public int SS_W_Y;
    public int SS_A_Y;
    public int SS_S_Y;
    public int SS_D_Y;
    public int SS_SPACE_Y;
    public int SS_ESC_Y;
    public int SS_BOMB_Y;
    public int SS_Q_Y;
    public int SS_E_Y;
    public int SS_T1_Y;
    public int SS_T2_Y;
    public int SS_T3_Y;
    public int SS_T1_HEIGHT;
    public int SS_T1_WIDTH;
    public int SS_T2_HEIGHT;
    public int SS_T2_WIDTH;
    public int SS_T3_HEIGHT;
    public int SS_T3_WIDTH;
    public int SS_FONT_SIZE;
    
    public Dimensions()
    {
    	try {
	    	Path path = Paths.get("parameters.txt");
	        Scanner scanner = new Scanner(path);
	        
	        FRAME_WIDTH = scanner.nextInt();
	        FRAME_HEIGHT= scanner.nextInt();
	        GAME_F_DIM= scanner.nextInt();
	        GAME_DIM= scanner.nextInt();
	        GAME_START= scanner.nextInt();
	        OBJ_DIM= scanner.nextInt();
	        BGD_CLR_A= scanner.nextInt();
	        BGD_CLR_B= scanner.nextInt();
	        BGD_CLR_C= scanner.nextInt();
	        FRAME_HEIGHT_GUI= scanner.nextInt();
	        WEIRD_X_CONSTANT= scanner.nextInt();
	        WEIRD_Y_CONSTANT= scanner.nextInt();
	        ANOTHER_WEIRD_Y_CONSTANT= scanner.nextInt();
	        BOMBBAR_X_MAIN = scanner.nextInt();
	    	BOMBBAR_Y_MAIN = scanner.nextInt();
	    	BOMBBAR_SX_MAIN = scanner.nextInt();
	    	BOMBBAR_SY_MAIN = scanner.nextInt();
	    	BOMBBAR_X_B1 = scanner.nextInt();
	    	BOMBBAR_Y_B1 = scanner.nextInt();
	    	BOMBBAR_SX_B1 = scanner.nextInt();
	    	BOMBBAR_SY_B1 = scanner.nextInt();
	    	BOMBBAR_X_B2 = scanner.nextInt();
	    	BOMBBAR_Y_B2 = scanner.nextInt();
	    	BOMBBAR_SX_B2 = scanner.nextInt();
	    	BOMBBAR_SY_B2 = scanner.nextInt();
	    	BOMBBAR_X_B3 = scanner.nextInt();
	    	BOMBBAR_Y_B3 = scanner.nextInt();
	    	BOMBBAR_SX_B3 = scanner.nextInt();
	    	BOMBBAR_SY_B3 = scanner.nextInt();
	    	BOMBBAR_X_B4 = scanner.nextInt();
	    	BOMBBAR_Y_B4 = scanner.nextInt();
	    	BOMBBAR_SX_B4 = scanner.nextInt();
	    	BOMBBAR_SY_B4 = scanner.nextInt();
	    	BOMBBAR_X_B5 = scanner.nextInt();
	    	BOMBBAR_Y_B5 = scanner.nextInt();
	    	BOMBBAR_SX_B5 = scanner.nextInt();
	    	BOMBBAR_SY_B5 = scanner.nextInt();
	    	HPBAR_XY_MAIN= scanner.nextInt();
	    	HPBAR_XS_MAIN= scanner.nextInt();
	    	HPBAR_SIZE= scanner.nextInt();
	    	HPBAR_X_1= scanner.nextInt();
	    	HPBAR_X_2= scanner.nextInt();
	    	HPBAR_X_3= scanner.nextInt();
	    	HPBAR_X_4= scanner.nextInt();
	    	HPBAR_X_5= scanner.nextInt();
	    	HPBAR_Y= scanner.nextInt();
	    	KG_FRAME_WIDTH = scanner.nextInt();
	        KG_FRAME_HEIGHT = scanner.nextInt();
	        KG_B1_X = scanner.nextInt();
	        KG_B_Y = scanner.nextInt();
	        KG_B_WIDTH = scanner.nextInt();
	        KG_B_HEIGHT = scanner.nextInt();
	        KG_B2_X = scanner.nextInt();
	        KG_T_X = scanner.nextInt();
	        KG_T_Y =scanner.nextInt();
	        KG_T_WIDTH =scanner.nextInt();
	        KG_T_HEIGHT =scanner.nextInt();
	        KG_FONT_SIZE =scanner.nextInt();
	        KG_FONTB_SIZE =scanner.nextInt();
	        KG_L1_X =scanner.nextInt();
	        KG_L1_Y =scanner.nextInt();
	        KG_L1_HEIGHT =scanner.nextInt();
	        KG_L1_WIDTH =scanner.nextInt();
	        
	        KG_L2_X =scanner.nextInt();
	        KG_L2_Y =scanner.nextInt();
	        KG_L2_HEIGHT =scanner.nextInt();
	        KG_L2_WIDTH =scanner.nextInt();
	        
	        KG_L3_X =scanner.nextInt();
	        KG_L3_Y =scanner.nextInt();
	        KG_L3_HEIGHT =scanner.nextInt();
	        KG_L3_WIDTH =scanner.nextInt();
	        
	        KG_L4_X =scanner.nextInt();
	        KG_L4_Y =scanner.nextInt();
	        KG_L4_HEIGHT =scanner.nextInt();
	        KG_L4_WIDTH =scanner.nextInt();
	        
	        KG_TF_X =scanner.nextInt();
	        KG_TF_Y =scanner.nextInt();
	        KG_TF_HEIGHT =scanner.nextInt();
	        KG_TF_WIDTH =scanner.nextInt();
	        
	        MAIN_FRAME_WIDTH =scanner.nextInt();
	         MAIN_FRAME_HEIGHT =scanner.nextInt();
	         B_WIDTH =scanner.nextInt();
	         B_HIGH =scanner.nextInt();
	         B_X =scanner.nextInt();
	         B1_Y =scanner.nextInt();
	         B2_Y =scanner.nextInt();
	         B3_Y =scanner.nextInt();
	         B4_Y =scanner.nextInt();
	         ANIMATIONS_CNT =scanner.nextInt();
	         
	          SCOREBAR_X_MAIN=scanner.nextInt();;
	     	 SCOREBAR_Y_MAIN=scanner.nextInt();;
	     	 SCOREBAR_XS_MAIN=scanner.nextInt();;
	     	 SCOREBAR_YS_MAIN=scanner.nextInt();;
	     	 SCOREBAR_X_ST=scanner.nextInt();;
	     	 SCOREBAR_Y_ST=scanner.nextInt();;
	     	 SCOREBAR_XS_ST=scanner.nextInt();;
	     	 SCOREBAR_YS_ST=scanner.nextInt();;
	     	 SCOREBAR_X_VAR=scanner.nextInt();;
	     	 SCOREBAR_Y_VAR=scanner.nextInt();;
	     	 SCOREBAR_XS_VAR=scanner.nextInt();;
	     	 SCOREBAR_YS_VAR=scanner.nextInt();;
	     	 
	          TIMEBAR_X_MAIN=scanner.nextInt();;
	     	 TIMEBAR_Y_MAIN=scanner.nextInt();;
	     	 TIMEBAR_XS_MAIN=scanner.nextInt();;
	     	 TIMEBAR_YS_MAIN=scanner.nextInt();;
	     	 TIMEBAR_X_ST=scanner.nextInt();;
	     	 TIMEBAR_Y_ST=scanner.nextInt();;
	     	 TIMEBAR_XS_ST=scanner.nextInt();;
	     	 TIMEBAR_YS_ST=scanner.nextInt();;
	     	 TIMEBAR_X_VAR=scanner.nextInt();;
	     	 TIMEBAR_Y_VAR=scanner.nextInt();;
	     	 TIMEBAR_XS_VAR=scanner.nextInt();;
	     	 TIMEBAR_YS_VAR=scanner.nextInt();;
	    	
	     	W_FRAME_WIDTH = scanner.nextInt();
	        W_FRAME_HEIGHT = scanner.nextInt();
	        W_B1_X = scanner.nextInt();
	        W_B_Y = scanner.nextInt();
	        W_B_WIDTH = scanner.nextInt();
	        W_B_HEIGHT = scanner.nextInt();
	        W_B2_X = scanner.nextInt();
	        W_T_X = scanner.nextInt();
	        W_T_Y =scanner.nextInt();
	        W_T_WIDTH =scanner.nextInt();
	        W_T_HEIGHT =scanner.nextInt();
	        W_FONT_SIZE =scanner.nextInt();
	        W_FONTB_SIZE =scanner.nextInt();
	        
	        S_FRAME_WIDTH=scanner.nextInt();
	        S_FRAME_HEIGHT=scanner.nextInt();
	        S_FONT_SIZE=scanner.nextInt();
	        S_FONTS_SIZE=scanner.nextInt();
	        S_T_X=scanner.nextInt();
	        S_T_Y=scanner.nextInt();
	        S_T_WIDTH=scanner.nextInt();
	        S_T_HEIGHT=scanner.nextInt();
	        S_SCROLL_X=scanner.nextInt();
	        S_SCROLL_Y=scanner.nextInt();
	        S_SCROLL_WIDTH=scanner.nextInt();
	        S_SCROLL_HEIGHT=scanner.nextInt();
	        
	        SS_FRAME_WIDTH=scanner.nextInt();
	        SS_FRAME_HEIGHT=scanner.nextInt();
	        SS_SIZE=scanner.nextInt();
	        SS_SPACE_HEIGHT=scanner.nextInt();
	        SS_SPACE_WIDTH=scanner.nextInt();
	        SS_FRONT_X=scanner.nextInt();
	        SS_BACK_X=scanner.nextInt();
	        SS_LEFT_X=scanner.nextInt();
	        SS_RIGHT_X=scanner.nextInt();
	        SS_W_X=scanner.nextInt();
	        SS_A_X=scanner.nextInt();
	        SS_S_X=scanner.nextInt();
	        SS_D_X=scanner.nextInt();
	        SS_SPACE_X=scanner.nextInt();
	        SS_ESC_X=scanner.nextInt();
	        SS_BOMB_X=scanner.nextInt();
	        SS_Q_X=scanner.nextInt();
	        SS_E_X=scanner.nextInt();
	        SS_T1_X=scanner.nextInt();
	        SS_T2_X=scanner.nextInt();
	        SS_T3_X=scanner.nextInt();
	        SS_FRONT_Y=scanner.nextInt();
	        SS_BACK_Y=scanner.nextInt();
	        SS_LEFT_Y=scanner.nextInt();
	        SS_RIGHT_Y=scanner.nextInt();
	        SS_W_Y=scanner.nextInt();
	        SS_A_Y=scanner.nextInt();
	        SS_S_Y=scanner.nextInt();
	        SS_D_Y=scanner.nextInt();
	        SS_SPACE_Y=scanner.nextInt();
	        SS_ESC_Y=scanner.nextInt();
	        SS_BOMB_Y=scanner.nextInt();
	        SS_Q_Y=scanner.nextInt();
	        SS_E_Y=scanner.nextInt();
	        SS_T1_Y=scanner.nextInt();
	        SS_T2_Y=scanner.nextInt();
	        SS_T3_Y=scanner.nextInt();
	        SS_T1_HEIGHT=scanner.nextInt();
	        SS_T1_WIDTH=scanner.nextInt();
	        SS_T2_HEIGHT=scanner.nextInt();
	        SS_T2_WIDTH=scanner.nextInt();
	        SS_T3_HEIGHT=scanner.nextInt();
	        SS_T3_WIDTH=scanner.nextInt();
	        SS_FONT_SIZE=scanner.nextInt();
	        
	        scanner.close();
    	} catch (FileNotFoundException e) {
			System.out.println("File not found");
		} catch (IOException e) {
			System.out.println("Error initializing stream");
		} 
    }
}
